default:
    trainer: ppo
    summary_freq: 5000
    batch_size: 128
    buffer_size: 2048
    hidden_units: 256
    learning_rate: 1.0e-3
    learning_rate_schedule: linear
    max_steps: 1.0e6
    normalize: false
    num_layers: 1
    time_horizon: 128
    beta: 1.0e-2
    epsilon: 0.3
    lambd: 0.95
    num_epoch: 7
    use_recurrent: false
    sequence_length: 64
    memory_size: 128
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.9
