default:
    trainer: ppo
    summary_freq: 200
    batch_size: 16
    buffer_size: 128
    hidden_units: 32
    learning_rate: 0.003
    beta: 5.0e-3
    epsilon: 0.25
    lambd: 0.98
    learning_rate_schedule: constant
    max_steps: 50000
    memory_size: 128
    normalize: false
    num_epoch: 5
    num_layers: 1
    time_horizon: 16
    sequence_length: 64
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.992
