default:
    trainer: ppo
    summary_freq: 50
    batch_size: 512
    buffer_size: 2048
    hidden_units: 32
    learning_rate: 1.0
    beta: 1.0e-3
    epsilon: 0.2
    lambd: 0.95
    learning_rate_schedule: linear
    max_steps: 1000
    memory_size: 128
    normalize: false
    num_epoch: 5
    num_layers: 1
    time_horizon: 32
    sequence_length: 64
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.995
