default:
    trainer: ppo
    summary_freq: 1000
    batch_size: 256
    buffer_size: 2048
    hidden_units: 32
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 6.0e6
    normalize: false
    num_layers: 1
    time_horizon: 512
    beta: 1.0e-3
    epsilon: 0.1
    lambd: 0.95
    num_epoch: 3
    use_recurrent: false
    sequence_length: 64
    memory_size: 128
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.9
